#!/bin/bash
cp -R configs/ /etc/adpushup
./helpers/dependencies
cd containers && docker-compose up -d && cd ..
./helpers/waitUntilCbReady
docker exec couchbase_container bash -c "/bin/bash /home/couchbaseInit"
docker cp cb_backup*.tar.gz couchbase_container:/home
docker exec couchbase_container bash -c "/bin/bash /home/restoreCb"

su -c "./helpers/apadminScript" apadmin
